server:
  port: 30001
spring:
  application:
    name: glow-server
  datasource:
    dbs:
      - cluster-label: user
        username: root
        password: root
        url: jdbc:mysql://localhost:3306/youpin?useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.xa.DruidXADataSource


